getCheckouts fundamentals
[*] - Added components for getCheckout implementation. Need to add html components.
[*] - Error: TS2551: Property 'getCheckouts' does not exist on type 'CheckoutsListComponent'.
[*] - created a gist to write down all the unknown stuff.